include = ["**/*.toml"]

[[rule]]
include = ["**/Cargo.toml"]
keys = ["workspace"]

[rule.formatting]
reorder_arrays = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["*-dependencies", "*.dependencies", "dependencies"]

[rule.formatting]
reorder_keys = true
